#!/bin/bash

set -o pipefail
start_time=$(date +%s)

curl -s -N -X POST "$LLM_URL/v1/chat/completions" \
  -H "Content-Type: application/json" \
  -d "{ \"messages\": [{\"role\": \"user\", \"content\": \"$*\"}], \"stream\":true }"

end_time=$(date +%s)
printf '\n%ds\n' $(($end_time - $start_time))
